version: '3.3'

services: 
  audit-node-modules-with-yara:
    image: audit-node-modules-with-yara
    build: 
      context: ../
      dockerfile: $PWD/Dockerfile
    volumes: 
      - ../:/opt/anwy/
    command: tail -f /dev/null